### ISSUE TITLE
Error Name :  Try again with -a option 

### ISSUE THREAD

**Issue by gituu4567** [Hax4us/Apkmod#115]
whenever i try to enable permission i got this 

I: Using Apktool 2.5.0-dirty on New55474.apk                                                                                                               
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/LiquidVIrus/.apkmod/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
[*] Decompiled into /tmp/tmp.dNvM2DxcgX
[*] Recompiling /tmp/tmp.dNvM2DxcgX                                                                                                                        
I: Using Apktool 2.5.0-dirty                                                                                                                               
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:919)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:344)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
        at brut.androlib.Androlib.buildSources(Androlib.java:351)
        at brut.androlib.Androlib.build(Androlib.java:303)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:259)
        at brut.apktool.Main.main(Main.java:85)
[!] Try again with -a option
But if still can't recompile, take screenshot and open a issue on github

**Comment by Hax4us** [comment]
what's your java version ?

**Comment by gituu4567** [comment]
I m using haxrat apk bro

**Comment by Dakota32** [comment]
> what's your java version ?

I have the same problem and when I use the `-a` parameter, I get this error:

`[!] Invalid option: -a`
